#pragma once
// This file is regenerated by scripts/patch_spotpear_factory.py after the
// SpotPear factory source is downloaded. Defaults keep local editors happy.
#define AURORA_FACTORY_HAS_SET_STATUS 1
#define AURORA_FACTORY_HAS_SET_CHAT_MESSAGE 1
#define AURORA_FACTORY_HAS_CLEAR_CHAT_MESSAGES 1
#define AURORA_FACTORY_HAS_SET_PREVIEW_IMAGE 0
#define AURORA_FACTORY_HAS_DISPLAY_LOCK_GUARD 1
